### ISSUE TITLE
Login Screen Moblie Styling Issue

### ISSUE THREAD

**Issue by samshoey07** [quantum-dash/quantum-dash#4]
If you enter the wrong password the popup covers the forms and you have to wait a pain-staking 3 seconds for that stupid, dumb box to disappear until you can guess at your password a second or third time. Can you fix that? Thanks, Jonathan. 

Wow this open source stuff is soooo much work. 

With Love,
Sam

**Comment by amayer5125** [comment]
This seems to still be an issue in the new bootstrap version but we are still looking into it.

**Comment by amayer5125** [comment]
This was fixed with b5d42e0e69eea7f863021e133afadfaf25042c52
